#define DEBUG

     // Get the hold of the active document
			Document doc=this.ActiveUIDocument.Document;
			Selection sel=this.ActiveUIDocument.Selection;
			
			// Create a new listener
			EventLogTraceListener eventLogTraceListener=
				new EventLogTraceListener("Application");
			Debug.Listeners.Add(eventLogTraceListener);
			
			try
			{
				Debug.WriteLine("Welcome!");
			}
			catch(Autodesk.Revit.Exceptions.OperationCanceledException)
			{
			}
			catch(Exception ex)
			{
				Debug.WriteLine(string.Format("StackTrace:\n{0}\nMessage:\n{1}",
				                              ex.StackTrace, ex.Message));
				
				TaskDialog.Show("Exception",string.Format("StackTrace:\n{0}\nMessage:\n{1}",
				                                          ex.StackTrace, ex.Message));
			}
			finally
			{
				Debug.Flush();
				Debug.Close();
			}
